# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: High Quality Screencasts for PHP, Java, web development, DevOps, and programming skills
email: team@bitpress.io
description: > # this means to ignore newlines until "baseurl:"
  High Quality Screencasts for PHP, Java, web development, DevOps, and programming skills
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bitpress.io" # the base hostname & protocol for your site
twitter_username: bitpressio
github_username:  bitpressio
paginate_path: "/blog/page:num/"
paginate: 10
permalink: pretty

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "BitPress Team"
      comments: false

authors:
  Jacob Jensen:
    name: Jacob Jensen
    bio: Jacob is a software engineer with a passion for teaching and deep experience in web development,design patterns, object oriented design, and a multitude of programming languages and platforms.
    gravitarId: 5460f254e076aea5d21e338b31c8ff36
    link: https://github.com/jjensen90
    github: https://github.com/jjensen90
  Paul Redmond:
    name: Paul Redmond
    bio: Hey, I'm Paul. I am a full stack developer. I write books like <a href="/docker-for-php-developers/">Docker for PHP Developers</a> and <a target="_blank" href="http://www.apress.com/us/book/9781484221860">Lumen Programming Guide</a> (Apress), and I write for <a href="https://laravel-news.com/@paulredmond">Laravel News</a>. I love PHP, Ruby, Node.js, DevOps, and Docker. 
    gravitarId: d9691184a54bfa1defe3dc7d625bc959
    link: https://github.com/paulredmond
    github: https://github.com/paulredmond
    github_handle: "paulredmond"
    twitter: https://twitter.com/paulredmond
    twitter_handle: "@paulredmond"
