# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: High Quality Screencasts for PHP, Java, web development, DevOps, and programming skills
email: team@bitpress.io
description: > # this means to ignore newlines until "baseurl:"
  High Quality Screencasts for PHP, Java, web development, DevOps, and programming skills
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bitpress.io" # the base hostname & protocol for your site
twitter_username: bitpressio
github_username:  bitpressio
paginate_path: "/blog/page:num/"
paginate: 10
permalink: pretty

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "BitPress Team"
      comments: true

authors:
  Jacob Jensen:
    name: Jacob Jensen
    bio: Jacob is a software engineer with a passion for teaching and deep experience in web development,design patterns, object oriented design, and a multitude of programming languages and platforms.
    gravitarId: 5460f254e076aea5d21e338b31c8ff36
    link: https://github.com/jjensen90
    github: https://github.com/jjensen90
  Paul Redmond:
    name: Paul Redmond
    bio: Paul is a full stack developer, author of <a target="_blank" href="https://leanpub.com/lumen-apis">Writing APIs with Lumen</a>, and a lover of PHP, Ruby, Node.js, DevOps, Docker, and tests.
    gravitarId: d9691184a54bfa1defe3dc7d625bc959
    link: https://github.com/paulredmond
    github: https://github.com/paulredmond
